
import React, { useRef } from 'react';
import { Asset } from '../types';
import { File, Image, Music, Film, MoreVertical, Folder, UploadCloud } from 'lucide-react';

interface AssetManagerProps {
    assets: Asset[];
    onAddAsset: (asset: Asset, fileBlob?: Blob) => void;
}

export const AssetManager: React.FC<AssetManagerProps> = ({ assets, onAddAsset }) => {
    const fileInputRef = useRef<HTMLInputElement>(null);

    const getIcon = (type: Asset['type']) => {
        switch(type) {
            case 'image': return <Image className="w-8 h-8 text-emerald-500" />;
            case 'audio': return <Music className="w-8 h-8 text-accent" />;
            case 'video': return <Film className="w-8 h-8 text-brand" />;
            default: return <File className="w-8 h-8 text-gray-400" />;
        }
    };

    const handleFileSelect = async (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files && e.target.files[0]) {
            const file = e.target.files[0];
            const type = file.type.startsWith('image/') ? 'image' : 
                         file.type.startsWith('audio/') ? 'audio' :
                         file.type.startsWith('video/') ? 'video' : 'document';
            
            const newAsset: Asset = {
                id: crypto.randomUUID(),
                name: file.name,
                type: type as any,
                url: '', // Will be generated by parent using blob
                size: `${(file.size / 1024 / 1024).toFixed(2)} MB`
            };

            onAddAsset(newAsset, file);
            
            // Reset input
            if (fileInputRef.current) fileInputRef.current.value = '';
        }
    };

    return (
        <div className="flex h-full bg-cream">
            {/* Folder Tree Sidebar */}
            <div className="w-64 border-r border-accent/20 bg-white p-4 hidden md:block shadow-sm">
                <h3 className="text-xs font-semibold text-grayText uppercase tracking-wider mb-4">Directories</h3>
                <ul className="space-y-1 text-sm">
                    <li className="flex items-center gap-2 px-3 py-2 bg-brand/5 text-brand rounded cursor-pointer border border-brand/20 font-medium">
                        <Folder className="w-4 h-4 fill-current" /> Local Storage
                    </li>
                    <li className="flex items-center gap-2 px-3 py-2 text-grayText hover:bg-gray-100 rounded cursor-pointer transition ml-4">
                        <span className="w-1 h-1 bg-gray-400 rounded-full"></span> Images
                    </li>
                    <li className="flex items-center gap-2 px-3 py-2 text-grayText hover:bg-gray-100 rounded cursor-pointer transition ml-4">
                        <span className="w-1 h-1 bg-gray-400 rounded-full"></span> Documents
                    </li>
                    <li className="flex items-center gap-2 px-3 py-2 text-grayText hover:bg-gray-100 rounded cursor-pointer transition ml-4">
                        <span className="w-1 h-1 bg-gray-400 rounded-full"></span> Audio
                    </li>
                </ul>
                
                <div className="mt-8 border-t border-gray-100 pt-4">
                    <div 
                        onClick={() => fileInputRef.current?.click()}
                        className="bg-gray-50 hover:bg-gray-100 p-4 rounded text-xs text-grayText text-center border border-dashed border-gray-300 cursor-pointer transition-colors group"
                    >
                        <UploadCloud className="w-6 h-6 mx-auto mb-2 text-gray-400 group-hover:text-brand transition-colors" />
                        Click to Upload <br/> to Local DB
                    </div>
                    <input 
                        type="file" 
                        ref={fileInputRef} 
                        className="hidden" 
                        onChange={handleFileSelect}
                    />
                </div>
            </div>

            {/* Main Grid */}
            <div className="flex-1 p-6 overflow-y-auto bg-cream">
                <header className="mb-6 flex justify-between items-center border-b border-accent/20 pb-4">
                    <div>
                        <h2 className="text-2xl font-bold text-brand">Asset Library</h2>
                        <p className="text-grayText text-sm">Files stored locally on your machine ({assets.length})</p>
                    </div>
                    <button onClick={() => fileInputRef.current?.click()} className="md:hidden bg-brand text-white p-2 rounded-lg">
                        <UploadCloud className="w-5 h-5" />
                    </button>
                </header>
                
                <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-5 gap-4">
                    {assets.map((asset) => (
                        <div key={asset.id} className="group relative bg-white rounded-lg border border-accent/20 hover:border-brand/50 hover:shadow-md transition-all p-4 flex flex-col items-center justify-center gap-3 aspect-square cursor-pointer">
                             {/* Preview Thumbnail Logic */}
                            {asset.type === 'image' ? (
                                <div className="w-full h-24 bg-gray-50 rounded overflow-hidden border border-gray-100">
                                    <img src={asset.url} alt={asset.name} className="w-full h-full object-cover group-hover:scale-105 transition-transform" />
                                </div>
                            ) : (
                                <div className="w-full h-24 bg-gray-50 rounded flex items-center justify-center border border-gray-100">
                                    {getIcon(asset.type)}
                                </div>
                            )}
                            
                            <div className="w-full text-center">
                                <p className="text-xs font-medium text-dark truncate w-full px-1" title={asset.name}>{asset.name}</p>
                                <p className="text-[10px] text-grayText mt-1">{asset.size || 'Local File'}</p>
                            </div>
                            
                            <div className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity">
                                <button className="p-1 hover:bg-gray-100 rounded"><MoreVertical className="w-4 h-4 text-gray-500" /></button>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
};
